### PR TITLE
how to patch msdosfs to mount EFI on safe mode boot

### PR DESCRIPTION
**Pull request by idoo**

### CODE REVIEW

**Comment by rafaelmaeuer** [comment]
why is this necessary? can't EFI be mounted using clover configurator in safe mode?

**Comment by idoo** [comment]
yes, because `msdosfs` kext not available without that patch

**Review by rafaelmaeuer — CHANGES_REQUESTED** [review]
please move to troubleshooting section

**Comment by idoo** [comment]
moved

**Pull request merged**
